AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tesla-battery-platform

Globals:
  Function:
    Timeout: 100
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  # ----------------------------------------------------------------
  # 1. DynamoDB Table
  # ----------------------------------------------------------------
  BatteryDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BatteryData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: battery_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: battery_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # ----------------------------------------------------------------
  # 2. Lambda Function
  # ----------------------------------------------------------------
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

      # Give the Lambda function an API Gateway event
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

      # Grant Lambda CRUD permissions on our DynamoDB table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BatteryDataTable

      # Pass the table name to the Lambda as an environment variable
      Environment:
        Variables:
          BATTERY_TABLE_NAME: !Ref BatteryDataTable

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn

  BatteryTableName:
    Description: "Name of the DynamoDB Table for battery data"
    Value: !Ref BatteryDataTable
