AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tesla-battery-platform

Globals:
  Function:
    Timeout: 100
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  # ----------------------------------------------------------------
  # 1. DynamoDB Table
  # ----------------------------------------------------------------
  BatteryDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BatteryData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: battery_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: battery_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # ----------------------------------------------------------------
  # 2. Lambda Function
  # ----------------------------------------------------------------
  BatteryDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: battery_data/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

      # (Optional) API Gateway event
      Events:
        GetBatteryDataApi:
          Type: Api
          Properties:
            Path: /battery_data
            Method: get

      # Grant Lambda CRUD permissions on our DynamoDB table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BatteryDataTable

      # Pass the table name to the Lambda as an environment variable
      Environment:
        Variables:
          BATTERY_TABLE_NAME: !Ref BatteryDataTable

Outputs:
  BatteryDataApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  BatteryDataFunctionArn:
    Description: Battery Data Lambda Function ARN
    Value: !GetAtt BatteryDataFunction.Arn

  BatteryDataFunctionIamRole:
    Description: Implicit IAM Role created for Battery Data function
    Value: !GetAtt BatteryDataFunctionRole.Arn

  BatteryTableName:
    Description: "Name of the DynamoDB Table for battery data"
    Value: !Ref BatteryDataTable
